import { Component } from 'react';
import { DropdownProps, DropdownState } from '../utils/types';
declare class Dropdown extends Component<DropdownProps, DropdownState> {
    static defaultProps: {
        ariaDescribedBy: null;
        ariaLabel: null;
        ariaLabelledBy: null;
        arrowRenderer: undefined;
        buttonClassName: undefined;
        centerText: boolean;
        contentClassName: null;
        disabled: boolean;
        height: null;
        hideArrow: boolean;
        id: null;
        maxContentHeight: null;
        multi: boolean;
        openUp: boolean;
        optionClassName: null;
        optionRenderer: undefined;
        options: never[];
        pageKeyTraverseSize: number;
        placeholder: string;
        searchable: boolean;
        selectedOption: null;
        selectedOptionClassName: null;
        selectedValueClassName: null;
        style: {};
        width: null;
    };
    state: DropdownState;
    private elements;
    private container;
    private button;
    constructor(props: DropdownProps);
    componentDidMount(): void;
    componentWillUnmount(): void;
    render(): JSX.Element;
    private renderValue;
    private renderArrow;
    private renderOptions;
    private onClick;
    private onDropdownClick;
    private onOptionClicked;
    private handleOptionRemove;
    private onKeyDown;
    private onNavigation;
    private getStyle;
    private setFocus;
    private closeDropdown;
    private searchDropdown;
    private searchList;
    private clearTimer;
    private clearSearch;
}
export default Dropdown;
